name: client
description: witness client

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^4.4.0+2
  http: ^0.13.4
  json_annotation: ^4.3.0
  logger: ^1.1.0
  progress_loader_overlay: ^3.0.1
  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.0
  matcher: ^0.12.10 # do not upgrade to ^0.12.11 because integration_test strictly depends on ^0.12.10


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
