name: client
description: witness client

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_speed_dial: ^6.2.0
  http: ^0.13.4
  injector: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  progress_loader_overlay: ^3.0.1
  provider: ^6.0.2
  reorderables: ^0.6.0
  timezone: ^0.9.1

dev_dependencies:
  build_runner: ^2.1.7
  firebase_auth_mocks: ^0.11.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  matcher: ^0.12.11
  mockito: ^5.1.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
