stages:
  - check
  - test

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # https://reset.inso.tuwien.ac.at/repo/help/ci/runners/configure_runners.md#git-strategy
  GIT_STRATEGY: clone

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

# Execute maven checkstyle plugin
check:server:
  image: maven:3.8-openjdk-15
  stage: check
  script:
    - 'cd server'
    - 'mvn $MAVEN_CLI_OPTS checkstyle:check'

# Check codestyle, linting and static analysis of client code with dartfmt
check:client:
  image: cirrusci/flutter:2.8.1
  stage: check
  script:
    - 'cd client'
    - 'flutter clean'
    - 'flutter pub get'
    - 'flutter pub run build_runner build'

    # Applies code formatting to project using dartfmt. Redirect stderr (2) to stdout (1) and send it to a file. If
    # this output (i.e. the formatted files) contains at least one line that ends with .dart, but NOT with .g.dart or .mocks.dart
    # (generated files may be formatted differently), the command on the last line returns 1, making the job fail.
    - 'dart format ./ --line-length 150 > formatResult.txt 2>&1 || true'
    - 'cat formatResult.txt'
    - if [ $(grep --perl-regexp 'Formatted[[:space:]].*(?<!\.(g|mocks))\.dart' formatResult.txt -c) != 0 ]; then exit 1; fi

    # The 'flutter analyze' may print parts of its output to stderr. Therefore, redirect stderr (2) to
    # stdout (1) and send it to a file. Finally, grep it for a positive outcome ("No issues found"). If this string
    # is not found (i.e. there are issues), grep exits with code 1, making the job fail. The " || true" part makes
    # that a potential non-zero exit code produced by the flutter analyze command does not make the job fail prematurely.
    - 'flutter analyze > analysisResult.txt 2>&1 || true'
    - 'cat analysisResult.txt'
    - 'grep "No issues found" analysisResult.txt'

# Run Java unit and integration tests
test:server:
  image: maven:3.8-openjdk-15
  stage: test
  needs:
    - check:server
  when: always
  script:
    - 'cd server'
    - 'mvn $MAVEN_CLI_OPTS clean verify'
  artifacts:
    when: always
    paths:
      - './server/logs/'
      - './server/target/surefire-reports/'
      # Filename (without extension) of API artifacts has to be kept in sync with the value of the LOCAL_FILE_NAME
      # constant in the server/src/test/java/com/witness/server/integration/web/ApiGenerationTest.java file.
      - './server/server_api.json'
      - './server/server_api.yaml'

# Execute Flutter unit tests
test:client:
  image: cirrusci/flutter:2.8.1
  stage: test
  needs:
    - check:client
  when: always
  script:
    - 'cd client'
    - 'flutter doctor --verbose'
    - 'flutter clean'
    - 'flutter pub get'
    - 'flutter pub run build_runner build'
    # Set environment variable for additional pub packages and activate them.
    - 'export PATH="$PATH":"$HOME/.pub-cache/bin"'
    - 'flutter pub global activate dart_dot_reporter'
    - 'flutter pub global activate junitreport'
    # Execute tests, save JSON output to file. junitreport converts the very verbose, raw JSON output into a more readable XML format
    # for further examinations. dart_dot_reporter creates a nice summary of the test execution from the JSON output for the CI logs.
    - 'flutter test --machine > flutter-test-report-raw.json || echo "[ERROR] Flutter Tests failed! See build artifacts for more details."'
    - 'flutter pub global run junitreport:tojunit --input flutter-test-report-raw.json --output flutter-test-report.xml'
    - 'flutter pub global run dart_dot_reporter flutter-test-report-raw.json --show-message --show-success --show-id'
  artifacts:
    when: always
    paths:
      - './client/flutter-test-report-raw.json'
      - './client/flutter-test-report.xml'
