logging:
  config: "@project.basedir@/logback.xml"
  directory: "@project.basedir@/logs"

spring:
  datasource:
    url: jdbc:h2:file:./database/server-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: password
  jpa:
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true